apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-date
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-date
            image: busybox
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - echo This cron job runs every minute
          restartPolicy: OnFailure