apiVersion: v1
kind: PersistentVolume
metadata:
  name: topics-history-pv-0
  labels:
    type: topics-history
spec:
  storageClassName: topics-history-storage-class
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/volumes/topics-history"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: topics-history-pv-1
  labels:
    type: topics-history
spec:
  storageClassName: topics-history-storage-class
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/volumes/topics-history"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: topics-history
  labels:
    app: topics-history
spec:
  selector:
    matchLabels:
      app: topics-history
  serviceName: topics-history-service
  replicas: 2
  template:
    metadata:
      labels:
        app: topics-history
    spec:
      containers:
        - name: topics-history-pod
          image: sergei-bodnar/topics-history
          env:
            - name: TOPICS_FILE_LOCATION
              value: /volume/topics-history.txt
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: topics-history-volume
            mountPath: /volume
          startupProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
  volumeClaimTemplates:
  - metadata:
      name: topics-history-volume
    spec:
      accessModes: [ ReadWriteOnce ]
      storageClassName: topics-history-storage-class
      resources:
        requests:
          storage: 1Mi
---
apiVersion: v1
kind: Service
metadata:
  name: topics-history-service
spec:
  type: NodePort
  selector:
    app: topics-history
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
